//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class participantTable
    {
        public string participantId { get; set; }
        public int playCode { get; set; }
        public int questoinCode { get; set; }
        public bool trueOrFalseAnswer { get; set; }
        public Nullable<int> timeOfRespond { get; set; }
    
        public virtual playTable playTable { get; set; }
        public virtual userTable userTable { get; set; }
    }
}
