//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class playTable
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public playTable()
        {
            this.participantTable = new HashSet<participantTable>();
        }
    
        public int playCode { get; set; }
        public int questionnaireCode { get; set; }
        public System.DateTime dateOfPlay { get; set; }
        public System.TimeSpan hourOfstartJoiningToPlay { get; set; }
        public System.TimeSpan hourOfstartPlay { get; set; }
        public System.TimeSpan hourOfEndPlay { get; set; }
        public string userIdCreator { get; set; }
        public string nameOfPlay { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<participantTable> participantTable { get; set; }
        public virtual questionnaireTable questionnaireTable { get; set; }
        public virtual userTable userTable { get; set; }
    }
}
