//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class questionTable
    {
        public int questionCode { get; set; }
        public int questionnaireCode { get; set; }
        public string contentsOfQuestion { get; set; }
        public string trueAnswer { get; set; }
        public string falseAnswer1 { get; set; }
        public string falseAnswer2 { get; set; }
        public string falseAnswer3 { get; set; }
        public decimal pointAnswer { get; set; }
    
        public virtual questionnaireTable questionnaireTable { get; set; }
    }
}
